version: "3"
services:
  frontend:
    container_name: phone_smiths_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ddiezr/web_phone_smiths
    ports:
      # env port variables for deployment purpose
      - 3000:3000
  backend:
    container_name: phone_smiths_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ddiezr/api_phone_smiths
    ports:
      # env port variables for deployment purpose
      - 5000:5000
