version: "3"
services:
  frontend:
    container_name: phone_smiths_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ddiezr/web_phone_smiths
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
  backend:
    container_name: phone_smiths_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ddiezr/api_phone_smiths
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
